### ISSUE TITLE
Cannot resolve keyword 'mobile' into field

### ISSUE THREAD

**Issue by zessbaa** [aaronn/django-rest-framework-passwordless#10]
Hi,

when i try to test the mobile authentication i get this error:

FieldError at /auth/mobile/ Cannot resolve keyword 'mobile' into field. Choices are: auth_token, callbacktoken, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username Request Method: POST Request URL: http://localhost:8000/auth/mobile/

And when i try to post without the key mobile i get a error says: mobile is a required field!

How can i solve thi problem? 

Thank you.

**Comment by aaronn** [comment]
You need to create a custom user model with the mobile field. This isn't really intended for use with the default django user model.
