### ISSUE TITLE
Bad request 400: Unable to send you a login code. Try again later.

### ISSUE THREAD

**Issue by jfornear** [aaronn/django-rest-framework-passwordless#138]
I have everything working correctly and expected in DEBUG.

In prod, I get this “Unable to send you a login code. Try again later.” bad request 400 error.

I've confirmed that my Twilio env is correct.

I see drfpasswordless is creating the User and callback tokens correctly. The issue is that no Twilio text is being sent.

**Comment by jfornear** [comment]
I forgot to add `twilio==8.10.3` to my `requirements.txt` 🤦‍♂️

**Comment by bhaveshdev09** [comment]
That may be the different case but In my case I have configured the wrong
email settings 😅
