### ISSUE TITLE
Invalid field name(s) for model User: 'mobile'.

### ISSUE THREAD

**Issue by manishhub9** [aaronn/django-rest-framework-passwordless#17]
Hello, i am following the docs and install these (pip freeze output):

certifi==2018.8.24
chardet==3.0.4
Django==2.1.1
djangorestframework==3.8.2
drfpasswordless==1.2.0
idna==2.7
oauthlib==2.1.0
pkg-resources==0.0.0
PyJWT==1.6.4
PySocks==1.6.8
pytz==2018.5
requests==2.19.1
six==1.11.0
twilio==6.16.4
urllib3==1.23

and when i am doing curl i am getting error. 

> curl -X POST -d "mobile=+918448876298" localhost:9001/auth/mobile/

FieldError at /auth/mobile/
Invalid field name(s) for model User: 'mobile'.

Request Method: POST
Request URL: http://localhost:9001/auth/mobile/
Django Version: 2.1.1
Python Executable: /home/bandar/restrobook/bin/python3.6
Python Version: 3.6.6

Please help me for resolving this issue. Thanks for your precious time.

**Comment by aaronn** [comment]
Did you create a custom model with the mobile field?

**Comment by taime** [comment]
Would somebody give an example of custom user model that works ?
