### ISSUE TITLE
Set unuseable password in AbstractBaseObtainAuthToken

### ISSUE THREAD

**Issue by SuperNascher** [aaronn/django-rest-framework-passwordless#19]
Hi,

should be the password only locked (in the post method from AbstractBaseObtainAuthToken),
if the user was created and not the Token was created?

https://github.com/aaronn/django-rest-framework-passwordless/blob/master/drfpasswordless/views.py#L133

**Comment by aaronn** [comment]
Yes, good point. Feel free to submit a PR, or I'll get to it when I can.

**Comment by SuperNascher** [comment]
You can check it at #22 ;-)
