### ISSUE TITLE
Does it work with non-US mobile numbers?

### ISSUE THREAD

**Issue by petrejonn** [aaronn/django-rest-framework-passwordless#2]
My api will be used by users from several countries i want to be sure there is no phone number restriction

**Comment by aaronn** [comment]
I've never tried Twilio with international numbers, but I assume yes. The serializer takes 9-15 digits, which should support the whole world

**Comment by souravjamwal77** [comment]
Hi @aaronn I'm from India and I can't send the Twilio SMS. Could please provide an example?
