### ISSUE TITLE
ObtainAuthTokenFromCallbackToken lacks AllowAny permissions

### ISSUE THREAD

**Issue by bwesen** [aaronn/django-rest-framework-passwordless#23]
I'm not sure how this module could work at all without AllowAny on the callback token post. We had to override this class and add

    permission_classes = (AllowAny,)

for it to work, as otherwise you can't post the 6-digit token as you're not logged in yet :)

The AllowAny is on the user registration endpoints (/account/auth/email etc.) but not on this...

**Comment by aaronn** [comment]
Good catch– thanks for spotting it.
