### ISSUE TITLE
Unable to send you a login code. Try again later.

### ISSUE THREAD

**Issue by afansv** [aaronn/django-rest-framework-passwordless#26]
Hello, everyone! I have a problem with sms auth using Twilio. That's my settings:

```
PASSWORDLESS_AUTH = {
    'PASSWORDLESS_AUTH_TYPES': ['MOBILE'],
    'PASSWORDLESS_MOBILE_NOREPLY_NUMBER': 'secret',
    'PASSWORDLESS_USER_MARK_MOBILE_VERIFIED': True,
}
```

And .env:
```
TWILIO_ACCOUNT_SID=secret
TWILIO_AUTH_TOKEN=secret
```

The problem is this error message (requesting **/auth/mobile/**):
```
{
    "detail": "Unable to send you a login code. Try again later."
}
```

Can you help me? I really upset about it. I don't think there is a problem with my Twilio credentials, because I have ho problem with this creds in console.

**Comment by taime** [comment]
@afansv
I've found out the problem!
The `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` in settings is not being used.
Actually this app use env vars.

This is code from  `utils.py`
````
twilio_client = Client(os.environ['TWILIO_ACCOUNT_SID'], os.environ['TWILIO_AUTH_TOKEN'])
````
As you can see... os.environ here!

So you should download this library and change this or export env vars to your environment: 

This would solve the problem!
**export TWILIO_ACCOUNT_SID=secret**
**export TWILIO_AUTH_TOKEN=secret**

**Comment by graycadeau** [comment]
Thank you @taime. Have had the same issue and this worked for me.

> @afansv
> I've found out the problem!
> The `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` in settings is not being used.
> Actually this app use env vars.
> 
> This is code from `utils.py`
> 
> ```
> twilio_client = Client(os.environ['TWILIO_ACCOUNT_SID'], os.environ['TWILIO_AUTH_TOKEN'])
> ```
> 
> As you can see... os.environ here!
> 
> So you should download this library and change this or export env vars to your environment:
> 
> This would solve the problem!
> **export TWILIO_ACCOUNT_SID=secret**
> **export TWILIO_AUTH_TOKEN=secret**

**Comment by aaronn** [comment]
Hey– this is mentioned in the readme:
```
and set the ``TWILIO_ACCOUNT_SID`` and ``TWILIO_AUTH_TOKEN`` environment
variables. 
```

I'll add some notes to make sure it's clearer that this is your environment and not settings file: 
```
These are read from `os.environ`, so make sure you don't put
them in your settings file accidentally.
```
