### ISSUE TITLE
Callback token being more than 6 digits would be a great

### ISSUE THREAD

**Issue by chachra** [aaronn/django-rest-framework-passwordless#3]
A random guid would be better than 123456 I think and more secure..

CallbackToken changes would be required. Would you be open to a PR?

**Comment by aaronn** [comment]
@chachra these are meant to be user friendly for memory– a lot of papers cite 7 ± 2 as the most comfortable for people to remember. A random GUID is certainly more secure, but you lose the point of this flow which is user-friendliness. I think 6 digits is secure enough when combined with an expiration time and no re-use.
