### ISSUE TITLE
Default Django user model doesn't work

### ISSUE THREAD

**Issue by SilvioMessi** [aaronn/django-rest-framework-passwordless#4]
I'm using like user model the default user model provided by Django (django.contrib.auth.models.User), but If I try to use more than one email I get this error _UNIQUE constraint failed: auth_user.username_.

Is it mandatory to create a custom user model?

**Comment by SilvioMessi** [comment]
Just for the record, a simple workaround is edit the line 51 of the file "django-rest-framework-passwordless/drfpasswordless/serializers.py" in this way:
`user, created = User.objects.get_or_create(**{self.alias_type: alias, "username": alias})`

**Comment by SilvioMessi** [comment]
@djstein sorry about my english.
In my opinion using the default user model (django.contrib.auth.models.User) to store the emails is the simplest solution, because you don't have to create a customized model. The main problem is that the default user model has the _username_ field that must be unique. So, if you want to use the default model, when you create a new user you must set the value of the  _username_  field as well. The pull request #11 fixes this problem. 
I opened this issue because it seemed strange to me that the default user model didn't work "out of the box".
I hope I have been clear this time.

**Comment by djstein** [comment]
@SilvioMessi thank you for the comment! I understand the confusion. However I am unsure if adding the alias as the username is the best approach. The situation will arise where a user's username will end up being their phone number, which seems incorrect.

I think that this package should not solve the issue of using DRF to create a user. It simply should be once a user has been created and verified that they then can use the token's to login over a password.

I also disagree with having a serializer create a user!

**Comment by jakeprem** [comment]
I agree that a user's username being their phone number seems incorrect.

In my particular use case I was just trying to minimize the amount of steps a user had to follow to sign in the application, and I was only using email, so it was sufficient to use their email as the username. It was also a fairly limited application.

Maybe it would be appropriate to add a flag in settings to allow using the user's email as their username? Something like `ENABLE_DEFAULT_USER_CREATION = True` for use cases where using the email/phone number entered is sufficient?

**Comment by djstein** [comment]
I understand what you are attempting to achieve, however I believe we should have this logic being handled in the view and NOT have a serializer (which is used to structure and destructure data) be creating a user. therefore refactoring this completely. 
I believe there are two options:
a. have the extra step, create a new view and serializer to handle user creation (by hand or use Django Rest Auth https://github.com/Tivix/django-rest-auth, example with this lib at https://github.com/modernproject/backend/tree/zappa). I believe this is a more correct approach, separation of actions.
b. in view's for auth, check request.data[alias] exists against a user  and if none:
1. pass the data to another view for creating a user
2. validating the data using a required attributes only user serializer
3. returning a success that the user has been created
4. prompt for login OR return a correct 6 dig token based on new setting LOGIN_ON_USER_REGISTRATION

**Comment by aaronn** [comment]
I think using the username field to store the email address or the mobile number is an OK quickfix hack if you really want to do this– but I agree with @djstein. Either way, this doesn't belong in the package. The more 'django compliant' way to do this would still be creating a custom model and setting the `USERNAME_FIELD` to email.
