### ISSUE TITLE
Support JWT & JWT Refreshing

### ISSUE THREAD

**Issue by aaronn** [aaronn/django-rest-framework-passwordless#44]
Recommend using this package, overriding the drfpasswordless token creation method (see `
PASSWORDLESS_AUTH_TOKEN_CREATOR 
` in `settings.py`) and hooking up the urls from this package:

https://github.com/davesque/django-rest-framework-simplejwt

**Comment by KhamidovAkbar** [comment]
Hey, can you please add an example on this to the docs.
Cheers!

**Comment by iNgredie** [comment]
> Hey, can you please add an example on this to the docs.
> Cheers!

did you find a way to do this?

**Comment by anuareramirez** [comment]
does someone find a way to do this?

**Comment by iNgredie** [comment]
> does someone find a way to do this?

https://github.com/iNgredie/spring2021/blob/main/src/users/serializers.py

**Comment by aaronsnig501** [comment]
@iNgredie This link doesn't work. Do you have an example of this?

**Comment by iNgredie** [comment]
in setting `'PASSWORDLESS_AUTH_TOKEN_SERIALIZER': 'src.users.serializers.JWTAuthTokenSerializer',  `
```
def get_token_for_user(user):
    return (AccessToken.for_user(user), None)
```

```  
class JWTAuthTokenSerializer(Serializer):
    access = serializers.CharField()

    def __init__(self, *args, **kwargs):
        user_id = kwargs['data']['payload']['user_id']
        self.user = User.objects.get(pk=user_id)
        super().__init__(*args, **kwargs)

    def validate(self, attrs):
        data = super().validate(attrs)
        token, _ = get_token_for_user(self.user)
        data['access'] = str(token)
        return data
```
