### ISSUE TITLE
on_delete required on AUTH_USER_MODEL foreign key

### ISSUE THREAD

**Issue by sslash** [aaronn/django-rest-framework-passwordless#5]
Currently, it's not possible to use this lib with Django 2.* as it requires an on_delete field on foreign key references: 
 (https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey).

**Comment by dkdndes** [comment]
drfpasswordless/models.py", line 38, in AbstractBaseCallbackToken
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name=None)

TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by MasterKale** [comment]
It appears @dkdndes has created a PR that should fix this issue: https://github.com/aaronn/django-rest-framework-passwordless/pull/6

**Comment by aaronn** [comment]
https://github.com/aaronn/django-rest-framework-passwordless/pull/6 merged
