### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by 1oglop1** [aaronn/django-rest-framework-passwordless#98]
Hi, I've noticed there haven't been any updates for over a year, I wonder if the project is still being maintained?

**Comment by zsoltbalint** [comment]
I am not sure if the project is active. I've seen recent issues here, where the owner wrote some comments. I assume the project isn't completely abandoned.

**Comment by aaronn** [comment]
It's not abandoned, I use it actively in a few projects but I can only update and maintain it when I actively need to change something.

Open to PRs or more active maintainers though.

**Comment by 1oglop1** [comment]
> It's not abandoned, I use it actively in a few projects but I can only update and maintain it when I actively need to change something.
> 
> Open to PRs or more active maintainers though.

This is good news, maybe you can leave this note in readme for awarenes and potential enthusiasts. I ended up not needing the  functionality though. 

But any updates, like bumping a python version in CI are a good indicator of the project activity.
